# Generated by Django 5.0.1 on 2024-03-27 16:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='injury',
            name='injury_age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='injury',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.player'),
        ),
        migrations.AlterField(
            model_name='player',
            name='date_of_birth',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='player',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
