# Generated by Django 5.0.1 on 2024-01-09 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_remove_player_age_injury_injured_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='date_of_birth',
            field=models.DateField(null=True),
        ),
    ]
