# Generated by Django 5.0.1 on 2024-01-10 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_alter_injury_injury_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='injury',
            name='injury_age',
            field=models.IntegerField(blank=True),
        ),
    ]
