# Generated by Django 5.0.1 on 2024-01-10 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_alter_injury_injury_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='injury',
            name='injury_end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
