# Generated by Django 5.0.1 on 2024-01-11 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_customuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='user_type',
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_business_user',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
