positions = [
    ("", "Select Position..."),
    ("Goalkeeper", "Goalkeeper"),
    ("Defender", "Defender"),
    ("Midfielder", "Midfielder"),
    ("Attacker", "Attacker"),
]

countries = [
    ("", "Select Country of Origin..."),
    ('Afghanistan', 'Afghanistan'), ('Aland Islands', 'Aland Islands'), ('Albania', 'Albania'), ('Algeria', 'Algeria'), ('American Samoa', 'American Samoa'), ('Andorra', 'Andorra'), 
    ('Angola', 'Angola'), ('Anguilla', 'Anguilla'), ('Antarctica', 'Antarctica'), ('Antigua and Barbuda', 'Antigua and Barbuda'), ('Argentina', 'Argentina'), ('Armenia', 'Armenia'), 
    ('Aruba', 'Aruba'), ('Australia', 'Australia'), ('Austria', 'Austria'), ('Azerbaijan', 'Azerbaijan'), ('Bahamas', 'Bahamas'), ('Bahrain', 'Bahrain'), ('Bangladesh', 'Bangladesh'), 
    ('Barbados', 'Barbados'), ('Belarus', 'Belarus'), ('Belgium', 'Belgium'), ('Belize', 'Belize'), ('Benin', 'Benin'), ('Bermuda', 'Bermuda'), ('Bhutan', 'Bhutan'), 
    ('Bolivia, Plurinational State of', 'Bolivia, Plurinational State of'), ('Bonaire, Sint Eustatius and Saba', 'Bonaire, Sint Eustatius and Saba'), 
    ('Bosnia and Herzegovina', 'Bosnia and Herzegovina'), ('Botswana', 'Botswana'), ('Bouvet Island', 'Bouvet Island'), ('Brazil', 'Brazil'), 
    ('British Indian Ocean Territory', 'British Indian Ocean Territory'), ('Brunei Darussalam', 'Brunei Darussalam'), ('Bulgaria', 'Bulgaria'), ('Burkina Faso', 'Burkina Faso'), 
    ('Burundi', 'Burundi'), ('Cambodia', 'Cambodia'), ('Cameroon', 'Cameroon'), ('Canada', 'Canada'), ('Cape Verde', 'Cape Verde'), ('Cayman Islands', 'Cayman Islands'), 
    ('Central African Republic', 'Central African Republic'), ('Chad', 'Chad'), ('Chile', 'Chile'), ('China', 'China'), ('Christmas Island', 'Christmas Island'), 
    ('Cocos (Keeling) Islands', 'Cocos (Keeling) Islands'), ('Colombia', 'Colombia'), ('Comoros', 'Comoros'), ('Congo', 'Congo'), 
    ('Congo, The Democratic Republic of the', 'Congo, The Democratic Republic of the'), ('Cook Islands', 'Cook Islands'), ('Costa Rica', 'Costa Rica'), ("Côte d'Ivoire", "Côte d'Ivoire"), 
    ('Croatia', 'Croatia'), ('Cuba', 'Cuba'), ('Curaçao', 'Curaçao'), ('Cyprus', 'Cyprus'), ('Czech Republic', 'Czech Republic'), ('Denmark', 'Denmark'), ('Djibouti', 'Djibouti'), 
    ('Dominica', 'Dominica'), ('Dominican Republic', 'Dominican Republic'), ('Ecuador', 'Ecuador'), ('Egypt', 'Egypt'), ('El Salvador', 'El Salvador'), ('Equatorial Guinea', 'Equatorial Guinea'), 
    ('Eritrea', 'Eritrea'), ('Estonia', 'Estonia'), ('Ethiopia', 'Ethiopia'), ('Falkland Islands (Malvinas)', 'Falkland Islands (Malvinas)'), ('Faroe Islands', 'Faroe Islands'), ('Fiji', 'Fiji'), 
    ('Finland', 'Finland'), ('France', 'France'), ('French Guiana', 'French Guiana'), ('French Polynesia', 'French Polynesia'), ('French Southern Territories', 'French Southern Territories'), 
    ('Gabon', 'Gabon'), ('Gambia', 'Gambia'), ('Georgia', 'Georgia'), ('Germany', 'Germany'), ('Ghana', 'Ghana'), ('Gibraltar', 'Gibraltar'), ('Greece', 'Greece'), ('Greenland', 'Greenland'), 
    ('Grenada', 'Grenada'), ('Guadeloupe', 'Guadeloupe'), ('Guam', 'Guam'), ('Guatemala', 'Guatemala'), ('Guernsey', 'Guernsey'), ('Guinea', 'Guinea'), ('Guinea-Bissau', 'Guinea-Bissau'), 
    ('Guyana', 'Guyana'), ('Haiti', 'Haiti'), ('Heard Island and McDonald Islands', 'Heard Island and McDonald Islands'), ('Holy See (Vatican City State)', 'Holy See (Vatican City State)'), 
    ('Honduras', 'Honduras'), ('Hong Kong', 'Hong Kong'), ('Hungary', 'Hungary'), ('Iceland', 'Iceland'), ('India', 'India'), ('Indonesia', 'Indonesia'), 
    ('Iran, Islamic Republic of', 'Iran, Islamic Republic of'), ('Iraq', 'Iraq'), ('Ireland', 'Ireland'), ('Isle of Man', 'Isle of Man'), ('Italy', 'Italy'), ('Jamaica', 'Jamaica'), 
    ('Japan', 'Japan'), ('Jersey', 'Jersey'), ('Jordan', 'Jordan'), ('Kazakhstan', 'Kazakhstan'), ('Kenya', 'Kenya'), ('Kiribati', 'Kiribati'), ('Korea', 'Korea'), ('Kuwait', 'Kuwait'), ('Kyrgyzstan', 'Kyrgyzstan'), 
    ("Lao People's Democratic Republic", "Lao People's Democratic Republic"), ('Latvia', 'Latvia'), ('Lebanon', 'Lebanon'), ('Lesotho', 'Lesotho'), ('Liberia', 'Liberia'), ('Libya', 'Libya'), 
    ('Liechtenstein', 'Liechtenstein'), ('Lithuania', 'Lithuania'), ('Luxembourg', 'Luxembourg'), ('Macao', 'Macao'), ('Macedonia', 'Macedonia'), 
    ('Madagascar', 'Madagascar'), ('Malawi', 'Malawi'), ('Malaysia', 'Malaysia'), ('Maldives', 'Maldives'), ('Mali', 'Mali'), ('Malta', 'Malta'), ('Marshall Islands', 'Marshall Islands'), 
    ('Martinique', 'Martinique'), ('Mauritania', 'Mauritania'), ('Mauritius', 'Mauritius'), ('Mayotte', 'Mayotte'), ('Mexico', 'Mexico'), ('Micronesia', 'Micronesia'), 
    ('Federated States of', 'Federated States of'), ('Moldova', 'Moldova'), ('Monaco', 'Monaco'), ('Mongolia', 'Mongolia'), ('Montenegro', 'Montenegro'), ('Montserrat', 'Montserrat'), 
    ('Morocco', 'Morocco'), ('Mozambique', 'Mozambique'), ('Myanmar', 'Myanmar'), ('Namibia', 'Namibia'), ('Nauru', 'Nauru'), ('Nepal', 'Nepal'), ('Netherlands', 'Netherlands'), 
    ('New Caledonia', 'New Caledonia'), ('New Zealand', 'New Zealand'), ('Nicaragua', 'Nicaragua'), ('Niger', 'Niger'), ('Nigeria', 'Nigeria'), ('Niue', 'Niue'), 
    ('Norfolk Island', 'Norfolk Island'), ('Northern Mariana Islands', 'Northern Mariana Islands'), ('Norway', 'Norway'), ('Oman', 'Oman'), ('Pakistan', 'Pakistan'), 
    ('Palau', 'Palau'), ('Palestine', 'Palestine'), ('Panama', 'Panama'), ('Papua New Guinea', 'Papua New Guinea'), ('Paraguay', 'Paraguay'), ('Peru', 'Peru'), ('Philippines', 'Philippines'), 
    ('Pitcairn', 'Pitcairn'), ('Poland', 'Poland'), ('Portugal', 'Portugal'), ('Puerto Rico', 'Puerto Rico'), ('Qatar', 'Qatar'), ('Réunion', 'Réunion'), ('Romania', 'Romania'), 
    ('Russian Federation', 'Russian Federation'), ('Rwanda', 'Rwanda'), ('Saint Barthélemy', 'Saint Barthélemy'), ('Saint Helena, Ascension and Tristan da Cunha', 'Saint Helena, Ascension and Tristan da Cunha'), 
    ('Saint Kitts and Nevis', 'Saint Kitts and Nevis'), ('Saint Lucia', 'Saint Lucia'), ('Saint Martin (French part)', 'Saint Martin (French part)'), 
    ('Saint Pierre and Miquelon', 'Saint Pierre and Miquelon'), ('Saint Vincent and the Grenadines', 'Saint Vincent and the Grenadines'), ('Samoa', 'Samoa'), ('San Marino', 'San Marino'), 
    ('Sao Tome and Principe', 'Sao Tome and Principe'), ('Saudi Arabia', 'Saudi Arabia'), ('Senegal', 'Senegal'), ('Serbia', 'Serbia'), ('Seychelles', 'Seychelles'), 
    ('Sierra Leone', 'Sierra Leone'), ('Singapore', 'Singapore'), ('Sint Maarten (Dutch part)', 'Sint Maarten (Dutch part)'), ('Slovakia', 'Slovakia'), ('Slovenia', 'Slovenia'), 
    ('Solomon Islands', 'Solomon Islands'), ('Somalia', 'Somalia'), ('South Africa', 'South Africa'), ('South Georgia and the South Sandwich Islands', 'South Georgia and the South Sandwich Islands'), 
    ('Spain', 'Spain'), ('Sri Lanka', 'Sri Lanka'), ('Sudan', 'Sudan'), ('Suriname', 'Suriname'), ('South Sudan', 'South Sudan'), ('Svalbard and Jan Mayen', 'Svalbard and Jan Mayen'), 
    ('Swaziland', 'Swaziland'), ('Sweden', 'Sweden'), ('Switzerland', 'Switzerland'), ('Syrian Arab Republic', 'Syrian Arab Republic'), ('Taiwan, Province of China', 'Taiwan, Province of China'), 
    ('Tajikistan', 'Tajikistan'), ('Tanzania, United Republic of', 'Tanzania, United Republic of'), ('Thailand', 'Thailand'), ('Timor-Leste', 'Timor-Leste'), ('Togo', 'Togo'), 
    ('Tokelau', 'Tokelau'), ('Tonga', 'Tonga'), ('Trinidad and Tobago', 'Trinidad and Tobago'), ('Tunisia', 'Tunisia'), ('Turkey', 'Turkey'), ('Turkmenistan', 'Turkmenistan'), 
    ('Turks and Caicos Islands', 'Turks and Caicos Islands'), ('Tuvalu', 'Tuvalu'), ('Uganda', 'Uganda'), ('Ukraine', 'Ukraine'), ('United Arab Emirates', 'United Arab Emirates'), 
    ('United Kingdom', 'United Kingdom'), ('United States', 'United States'), ('United States Minor Outlying Islands', 'United States Minor Outlying Islands'), ('Uruguay', 'Uruguay'), 
    ('Uzbekistan', 'Uzbekistan'), ('Vanuatu', 'Vanuatu'), ('Venezuela, Bolivarian Republic of', 'Venezuela, Bolivarian Republic of'), ('Viet Nam', 'Viet Nam'), 
    ('Virgin Islands, British', 'Virgin Islands, British'), ('Virgin Islands, U.S.', 'Virgin Islands, U.S.'), ('Wallis and Futuna', 'Wallis and Futuna'), ('Yemen', 'Yemen'), 
    ('Zambia', 'Zambia'), ('Zimbabwe', 'Zimbabwe')
    ]

injuries = [
    ("", "Select Injury..."),
    ('ankle problems', 'ankle problems'), ('broken kneecap', 'broken kneecap'), ('patellar tendon rupture', 'patellar tendon rupture'), ('knee injury', 'knee injury'), 
    ('cruciate ligament tear', 'cruciate ligament tear'), ('patellar tendon dislocation', 'patellar tendon dislocation'), ('cruciate ligament strain', 'cruciate ligament strain'), 
    ('patellar tendinopathy syndrome', 'patellar tendinopathy syndrome'), ('knee collateral ligament tear', 'knee collateral ligament tear'), ('ligament tear', 'ligament tear'), 
    ('outer ligament tear', 'outer ligament tear'), ('knee medial ligament tear', 'knee medial ligament tear'), ('internal ligament strain', 'internal ligament strain'), 
    ('cruciate ligament injury', 'cruciate ligament injury'), ('torn lateral knee ligament', 'torn lateral knee ligament'), 
    ('inner ligament tear in ankle joint', 'inner ligament tear in ankle joint'), ('outer ligament problems', 'outer ligament problems'), 
    ('ankle ligament tear', 'ankle ligament tear'), ('leg injury', 'leg injury'), ('achilles tendon rupture', 'achilles tendon rupture'), ('ligament stretching', 'ligament stretching'), 
    ('broken ankle', 'broken ankle'), ('collateral ligament tear', 'collateral ligament tear'), ('internal ligament tear', 'internal ligament tear'), ('ankle injury', 'ankle injury'),
    ('tendon tear', 'tendon tear'), ('inner ankle ligament tear', 'inner ankle ligament tear'), ('broken leg', 'broken leg'), 
    ('syndesmotic ligament tear', 'syndesmotic ligament tear'), ('inflammation in the ankle joint', 'inflammation in the ankle joint'), 
    ('torn ligaments in the tarsus', 'torn ligaments in the tarsus'), ('torn ligaments', 'torn ligaments'), 
    ('partial damage to the cruciate ligament', 'partial damage to the cruciate ligament'), ('edema in the knee', 'edema in the knee'), 
    ('double ligament tear', 'double ligament tear'), ('ligament injury', 'ligament injury'), ('inner knee ligament tear', 'inner knee ligament tear'), 
    ('inflammation of ligaments in the knee', 'inflammation of ligaments in the knee'), ('collateral ankle ligament tear', 'collateral ankle ligament tear'), 
    ('injury to the ankle', 'injury to the ankle'), ('patellar tendon tear', 'patellar tendon tear'), ('bruise on ankle', 'bruise on ankle'), ('ankle sprain', 'ankle sprain'), 
    ('inner ligament stretch of the knee', 'inner ligament stretch of the knee'), ('capsular tear of ankle joint', 'capsular tear of ankle joint'), 
    ('inflammation of the biceps tendon in the thigh', 'inflammation of the biceps tendon in the thigh'), ('collateral ligament injury', 'collateral ligament injury'), 
    ('overstretching of the syndesmotic ligament', 'overstretching of the syndesmotic ligament'), ('knee collateral ligament strain', 'knee collateral ligament strain'), 
    ('torn knee ligaments', 'torn knee ligaments'), (' achilles tendon contusion', ' achilles tendon contusion'), ('achilles tendon irritation', 'achilles tendon irritation'), 
    ('ankle surgery', 'ankle surgery'), ('tendon irritation', 'tendon irritation'), ('tendon rupture', 'tendon rupture'), ('torn lateral ankle ligament', 'torn lateral ankle ligament'), 
    ('cyst in the knee', 'cyst in the knee'), ('partial patellar tendon tear', 'partial patellar tendon tear'), ('inflammation in the knee', 'inflammation in the knee'), 
    ('torn ankle ligaments', 'torn ankle ligaments'), ('inner ligament injury', 'inner ligament injury'), ('bruised knee', 'bruised knee'), 
    ('cruciate ligament surgery', 'cruciate ligament surgery'), ('tendonitis', 'tendonitis'), ('patellar tendon irritation', 'patellar tendon irritation'), 
    ('longitudinal tendon tear', 'longitudinal tendon tear'), ('knee surgery', 'knee surgery'), ('dislocation fracture of the ankle joint', 'dislocation fracture of the ankle joint'), 
    ('achilles tendon surgery', 'achilles tendon surgery'), ('achilles tendon problems', 'achilles tendon problems'), ('knee problems', 'knee problems'), 
    ('dislocation of the kneecap', 'dislocation of the kneecap'), ('peroneus tendon injury', 'peroneus tendon injury'), ('bruise on the ankle joint', 'bruise on the ankle joint'), 
    ('knee bruise', 'knee bruise'), ('syndesmosis ligament tear', 'syndesmosis ligament tear'), ('lower leg fracture', 'lower leg fracture'), 
    ('patellar tendon problems', 'patellar tendon problems')
    ]