positions = [
    ("", "Select Position..."),
    ("Goalkeeper", "Goalkeeper"),
    ("Defender", "Defender"),
    ("Midfielder", "Midfielder"),
    ("Attacker", "Attacker"),
]

countries = [
    ("", "Select Country of Origin..."),
    ('Afghanistan', 'Afghanistan'), ('Aland Islands', 'Aland Islands'), ('Albania', 'Albania'), ('Algeria', 'Algeria'), ('American Samoa', 'American Samoa'), ('Andorra', 'Andorra'), 
    ('Angola', 'Angola'), ('Anguilla', 'Anguilla'), ('Antarctica', 'Antarctica'), ('Antigua and Barbuda', 'Antigua and Barbuda'), ('Argentina', 'Argentina'), ('Armenia', 'Armenia'), 
    ('Aruba', 'Aruba'), ('Australia', 'Australia'), ('Austria', 'Austria'), ('Azerbaijan', 'Azerbaijan'), ('Bahamas', 'Bahamas'), ('Bahrain', 'Bahrain'), ('Bangladesh', 'Bangladesh'), 
    ('Barbados', 'Barbados'), ('Belarus', 'Belarus'), ('Belgium', 'Belgium'), ('Belize', 'Belize'), ('Benin', 'Benin'), ('Bermuda', 'Bermuda'), ('Bhutan', 'Bhutan'), 
    ('Bolivia, Plurinational State of', 'Bolivia, Plurinational State of'), ('Bonaire, Sint Eustatius and Saba', 'Bonaire, Sint Eustatius and Saba'), 
    ('Bosnia and Herzegovina', 'Bosnia and Herzegovina'), ('Botswana', 'Botswana'), ('Bouvet Island', 'Bouvet Island'), ('Brazil', 'Brazil'), 
    ('British Indian Ocean Territory', 'British Indian Ocean Territory'), ('Brunei Darussalam', 'Brunei Darussalam'), ('Bulgaria', 'Bulgaria'), ('Burkina Faso', 'Burkina Faso'), 
    ('Burundi', 'Burundi'), ('Cambodia', 'Cambodia'), ('Cameroon', 'Cameroon'), ('Canada', 'Canada'), ('Cape Verde', 'Cape Verde'), ('Cayman Islands', 'Cayman Islands'), 
    ('Central African Republic', 'Central African Republic'), ('Chad', 'Chad'), ('Chile', 'Chile'), ('China', 'China'), ('Christmas Island', 'Christmas Island'), 
    ('Cocos (Keeling) Islands', 'Cocos (Keeling) Islands'), ('Colombia', 'Colombia'), ('Comoros', 'Comoros'), ('Congo', 'Congo'), 
    ('Congo, The Democratic Republic of the', 'Congo, The Democratic Republic of the'), ('Cook Islands', 'Cook Islands'), ('Costa Rica', 'Costa Rica'), ("Côte d'Ivoire", "Côte d'Ivoire"), 
    ('Croatia', 'Croatia'), ('Cuba', 'Cuba'), ('Curaçao', 'Curaçao'), ('Cyprus', 'Cyprus'), ('Czech Republic', 'Czech Republic'), ('Denmark', 'Denmark'), ('Djibouti', 'Djibouti'), 
    ('Dominica', 'Dominica'), ('Dominican Republic', 'Dominican Republic'), ('Ecuador', 'Ecuador'), ('Egypt', 'Egypt'), ('El Salvador', 'El Salvador'), ('Equatorial Guinea', 'Equatorial Guinea'), 
    ('Eritrea', 'Eritrea'), ('Estonia', 'Estonia'), ('Ethiopia', 'Ethiopia'), ('Falkland Islands (Malvinas)', 'Falkland Islands (Malvinas)'), ('Faroe Islands', 'Faroe Islands'), ('Fiji', 'Fiji'), 
    ('Finland', 'Finland'), ('France', 'France'), ('French Guiana', 'French Guiana'), ('French Polynesia', 'French Polynesia'), ('French Southern Territories', 'French Southern Territories'), 
    ('Gabon', 'Gabon'), ('Gambia', 'Gambia'), ('Georgia', 'Georgia'), ('Germany', 'Germany'), ('Ghana', 'Ghana'), ('Gibraltar', 'Gibraltar'), ('Greece', 'Greece'), ('Greenland', 'Greenland'), 
    ('Grenada', 'Grenada'), ('Guadeloupe', 'Guadeloupe'), ('Guam', 'Guam'), ('Guatemala', 'Guatemala'), ('Guernsey', 'Guernsey'), ('Guinea', 'Guinea'), ('Guinea-Bissau', 'Guinea-Bissau'), 
    ('Guyana', 'Guyana'), ('Haiti', 'Haiti'), ('Heard Island and McDonald Islands', 'Heard Island and McDonald Islands'), ('Holy See (Vatican City State)', 'Holy See (Vatican City State)'), 
    ('Honduras', 'Honduras'), ('Hong Kong', 'Hong Kong'), ('Hungary', 'Hungary'), ('Iceland', 'Iceland'), ('India', 'India'), ('Indonesia', 'Indonesia'), 
    ('Iran, Islamic Republic of', 'Iran, Islamic Republic of'), ('Iraq', 'Iraq'), ('Ireland', 'Ireland'), ('Isle of Man', 'Isle of Man'), ('Italy', 'Italy'), ('Jamaica', 'Jamaica'), 
    ('Japan', 'Japan'), ('Jersey', 'Jersey'), ('Jordan', 'Jordan'), ('Kazakhstan', 'Kazakhstan'), ('Kenya', 'Kenya'), ('Kiribati', 'Kiribati'), ('Korea', 'Korea'), ('Kuwait', 'Kuwait'), ('Kyrgyzstan', 'Kyrgyzstan'), 
    ("Lao People's Democratic Republic", "Lao People's Democratic Republic"), ('Latvia', 'Latvia'), ('Lebanon', 'Lebanon'), ('Lesotho', 'Lesotho'), ('Liberia', 'Liberia'), ('Libya', 'Libya'), 
    ('Liechtenstein', 'Liechtenstein'), ('Lithuania', 'Lithuania'), ('Luxembourg', 'Luxembourg'), ('Macao', 'Macao'), ('Macedonia', 'Macedonia'), 
    ('Madagascar', 'Madagascar'), ('Malawi', 'Malawi'), ('Malaysia', 'Malaysia'), ('Maldives', 'Maldives'), ('Mali', 'Mali'), ('Malta', 'Malta'), ('Marshall Islands', 'Marshall Islands'), 
    ('Martinique', 'Martinique'), ('Mauritania', 'Mauritania'), ('Mauritius', 'Mauritius'), ('Mayotte', 'Mayotte'), ('Mexico', 'Mexico'), ('Micronesia', 'Micronesia'), 
    ('Federated States of', 'Federated States of'), ('Moldova', 'Moldova'), ('Monaco', 'Monaco'), ('Mongolia', 'Mongolia'), ('Montenegro', 'Montenegro'), ('Montserrat', 'Montserrat'), 
    ('Morocco', 'Morocco'), ('Mozambique', 'Mozambique'), ('Myanmar', 'Myanmar'), ('Namibia', 'Namibia'), ('Nauru', 'Nauru'), ('Nepal', 'Nepal'), ('Netherlands', 'Netherlands'), 
    ('New Caledonia', 'New Caledonia'), ('New Zealand', 'New Zealand'), ('Nicaragua', 'Nicaragua'), ('Niger', 'Niger'), ('Nigeria', 'Nigeria'), ('Niue', 'Niue'), 
    ('Norfolk Island', 'Norfolk Island'), ('Northern Mariana Islands', 'Northern Mariana Islands'), ('Norway', 'Norway'), ('Oman', 'Oman'), ('Pakistan', 'Pakistan'), 
    ('Palau', 'Palau'), ('Palestine', 'Palestine'), ('Panama', 'Panama'), ('Papua New Guinea', 'Papua New Guinea'), ('Paraguay', 'Paraguay'), ('Peru', 'Peru'), ('Philippines', 'Philippines'), 
    ('Pitcairn', 'Pitcairn'), ('Poland', 'Poland'), ('Portugal', 'Portugal'), ('Puerto Rico', 'Puerto Rico'), ('Qatar', 'Qatar'), ('Réunion', 'Réunion'), ('Romania', 'Romania'), 
    ('Russian Federation', 'Russian Federation'), ('Rwanda', 'Rwanda'), ('Saint Barthélemy', 'Saint Barthélemy'), ('Saint Helena, Ascension and Tristan da Cunha', 'Saint Helena, Ascension and Tristan da Cunha'), 
    ('Saint Kitts and Nevis', 'Saint Kitts and Nevis'), ('Saint Lucia', 'Saint Lucia'), ('Saint Martin (French part)', 'Saint Martin (French part)'), 
    ('Saint Pierre and Miquelon', 'Saint Pierre and Miquelon'), ('Saint Vincent and the Grenadines', 'Saint Vincent and the Grenadines'), ('Samoa', 'Samoa'), ('San Marino', 'San Marino'), 
    ('Sao Tome and Principe', 'Sao Tome and Principe'), ('Saudi Arabia', 'Saudi Arabia'), ('Senegal', 'Senegal'), ('Serbia', 'Serbia'), ('Seychelles', 'Seychelles'), 
    ('Sierra Leone', 'Sierra Leone'), ('Singapore', 'Singapore'), ('Sint Maarten (Dutch part)', 'Sint Maarten (Dutch part)'), ('Slovakia', 'Slovakia'), ('Slovenia', 'Slovenia'), 
    ('Solomon Islands', 'Solomon Islands'), ('Somalia', 'Somalia'), ('South Africa', 'South Africa'), ('South Georgia and the South Sandwich Islands', 'South Georgia and the South Sandwich Islands'), 
    ('Spain', 'Spain'), ('Sri Lanka', 'Sri Lanka'), ('Sudan', 'Sudan'), ('Suriname', 'Suriname'), ('South Sudan', 'South Sudan'), ('Svalbard and Jan Mayen', 'Svalbard and Jan Mayen'), 
    ('Swaziland', 'Swaziland'), ('Sweden', 'Sweden'), ('Switzerland', 'Switzerland'), ('Syrian Arab Republic', 'Syrian Arab Republic'), ('Taiwan, Province of China', 'Taiwan, Province of China'), 
    ('Tajikistan', 'Tajikistan'), ('Tanzania, United Republic of', 'Tanzania, United Republic of'), ('Thailand', 'Thailand'), ('Timor-Leste', 'Timor-Leste'), ('Togo', 'Togo'), 
    ('Tokelau', 'Tokelau'), ('Tonga', 'Tonga'), ('Trinidad and Tobago', 'Trinidad and Tobago'), ('Tunisia', 'Tunisia'), ('Turkey', 'Turkey'), ('Turkmenistan', 'Turkmenistan'), 
    ('Turks and Caicos Islands', 'Turks and Caicos Islands'), ('Tuvalu', 'Tuvalu'), ('Uganda', 'Uganda'), ('Ukraine', 'Ukraine'), ('United Arab Emirates', 'United Arab Emirates'), 
    ('United Kingdom', 'United Kingdom'), ('United States', 'United States'), ('United States Minor Outlying Islands', 'United States Minor Outlying Islands'), ('Uruguay', 'Uruguay'), 
    ('Uzbekistan', 'Uzbekistan'), ('Vanuatu', 'Vanuatu'), ('Venezuela, Bolivarian Republic of', 'Venezuela, Bolivarian Republic of'), ('Viet Nam', 'Viet Nam'), 
    ('Virgin Islands, British', 'Virgin Islands, British'), ('Virgin Islands, U.S.', 'Virgin Islands, U.S.'), ('Wallis and Futuna', 'Wallis and Futuna'), ('Yemen', 'Yemen'), 
    ('Zambia', 'Zambia'), ('Zimbabwe', 'Zimbabwe')
    ]

injuries = [
    ('', 'Select injury...'), (' Achilles tendon contusion', ' Achilles tendon contusion'), ('Achilles tendon irritation', 'Achilles tendon irritation'), 
    ('Achilles tendon problems', 'Achilles tendon problems'), ('Achilles tendon rupture', 'Achilles tendon rupture'), ('Achilles tendon surgery', 'Achilles tendon surgery'), 
    ('Ankle injury', 'Ankle injury'), ('Ankle ligament tear', 'Ankle ligament tear'), ('Ankle problems', 'Ankle problems'), 
    ('Ankle sprain', 'Ankle sprain'), ('Ankle surgery', 'Ankle surgery'), ('Broken ankle', 'Broken ankle'), 
    ('Broken kneecap', 'Broken kneecap'), ('Broken leg', 'Broken leg'), ('Bruise on ankle', 'Bruise on ankle'), 
    ('Bruise on the ankle joint', 'Bruise on the ankle joint'), ('Bruised knee', 'Bruised knee'), ('Capsular tear of ankle joint', 'Capsular tear of ankle joint'), 
    ('Collateral ankle ligament tear', 'Collateral ankle ligament tear'), ('Collateral ligament injury', 'Collateral ligament injury'), 
    ('Collateral ligament tear', 'Collateral ligament tear'), ('Cruciate ligament injury', 'Cruciate ligament injury'), 
    ('Cruciate ligament strain', 'Cruciate ligament strain'), ('Cruciate ligament surgery', 'Cruciate ligament surgery'), 
    ('Cruciate ligament tear', 'Cruciate ligament tear'), ('Cyst in the knee', 'Cyst in the knee'), 
    ('Dislocation fracture of the ankle joint', 'Dislocation fracture of the ankle joint'), ('Dislocation of the kneecap', 'Dislocation of the kneecap'), ('Double ligament tear', 'Double ligament tear'), 
    ('Edema in the knee', 'Edema in the knee'), ('Inflammation in the ankle joint', 'Inflammation in the ankle joint'), 
    ('Inflammation in the knee', 'Inflammation in the knee'), ('Inflammation of ligaments in the knee', 'Inflammation of ligaments in the knee'), 
    ('Inflammation of the biceps tendon in the thigh', 'Inflammation of the biceps tendon in the thigh'), ('Injury to the ankle', 'Injury to the ankle'), 
    ('Inner ankle ligament tear', 'Inner ankle ligament tear'), ('Inner knee ligament tear', 'Inner knee ligament tear'), 
    ('Inner ligament injury', 'Inner ligament injury'), ('Inner ligament stretch of the knee', 'Inner ligament stretch of the knee'), 
    ('Inner ligament tear in ankle joint', 'Inner ligament tear in ankle joint'), ('Internal ligament strain', 'Internal ligament strain'), 
    ('Internal ligament tear', 'Internal ligament tear'), ('Knee bruise', 'Knee bruise'), ('Knee collateral ligament strain', 'Knee collateral ligament strain'), 
    ('Knee collateral ligament tear', 'Knee collateral ligament tear'), ('Knee injury', 'Knee injury'), ('Knee medial ligament tear', 'Knee medial ligament tear'), 
    ('Knee problems', 'Knee problems'), ('Knee surgery', 'Knee surgery'), ('Leg injury', 'Leg injury'), ('Ligament injury', 'Ligament injury'), 
    ('Ligament stretching', 'Ligament stretching'), ('Ligament tear', 'Ligament tear'), ('Longitudinal tendon tear', 'Longitudinal tendon tear'), 
    ('Lower leg fracture', 'Lower leg fracture'), ('Outer ligament problems', 'Outer ligament problems'), ('Outer ligament tear', 'Outer ligament tear'), 
    ('Overstretching of the syndesmotic ligament', 'Overstretching of the syndesmotic ligament'), ('Partial damage to the cruciate ligament', 'Partial damage to the cruciate ligament'), 
    ('Partial patellar tendon tear', 'Partial patellar tendon tear'), ('Patellar tendinopathy syndrome', 'Patellar tendinopathy syndrome'), 
    ('Patellar tendon dislocation', 'Patellar tendon dislocation'), ('Patellar tendon irritation', 'Patellar tendon irritation'), 
    ('Patellar tendon problems', 'Patellar tendon problems'), ('Patellar tendon rupture', 'Patellar tendon rupture'), 
    ('Patellar tendon tear', 'Patellar tendon tear'), ('Peroneus tendon injury', 'Peroneus tendon injury'), 
    ('Syndesmosis ligament tear', 'Syndesmosis ligament tear'), ('Syndesmotic ligament tear', 'Syndesmotic ligament tear'), 
    ('Tendon irritation', 'Tendon irritation'), ('Tendon rupture', 'Tendon rupture'), ('Tendon tear', 'Tendon tear'), 
    ('Tendonitis', 'Tendonitis'), ('Torn ankle ligaments', 'Torn ankle ligaments'), ('Torn knee ligaments', 'Torn knee ligaments'), 
    ('Torn lateral ankle ligament', 'Torn lateral ankle ligament'), ('Torn lateral knee ligament', 'Torn lateral knee ligament'), 
    ('Torn ligaments', 'Torn ligaments'), ('Torn ligaments in the tarsus', 'Torn ligaments in the tarsus')
    ]